name: Metrics
on:
  schedule:
    - cron: "0 0-23/4 * * *"
  push:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:

      - name: ðŸ¦‘ Personal metrics
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: header
          template: classic
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_introduction: yes
          plugin_introduction_title: no # Hide section title
          plugin_languages_ignored: html, vue, scala, c, ejs
          plugin_languages_skipped: Mehak-Mehta
          plugin_languages_details: bytes-size, percentage
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: mastered
          plugin_notable: yes
          config_order: base.header, isocalendar, languages, notable, topics
          plugin_traffic: yes
          plugin_habits: yes
          plugin_habits_from: 200       # Use 200 events to compute habits
          plugin_habits_days: 14        # Keep only events from last 14 days
      - name: ðŸ“Œ Topics plugin (mastered)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.topics.mastered.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: mastered
          plugins_errors_fatal: ${{ github.repository == 'Mehak-Mehta' }}
          output_action: pull-request
          
      - name: ðŸ“Œ Aci (mastered)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.personal.active.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 5    # Limit to 5 events
          plugin_activity_days: 14    # Keep only events from last 14 days (can be set to 0 to disable limitations)
          plugin_activity_filter: all # Show all events (use table above to filter events types)
      
      - name: habits
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
         filename: metrics.personal.habits.svg
         token: ${{ secrets.METRICS_TOKEN }}
         base: ""
        
         config_timezone: Asia/Kolkata # Set timezone
         
      - name: ðŸ“Œ Topics plugin (mastered)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.topics.masteredd.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: mastered
          plugins_errors_fatal: ${{ github.repository == 'Mehak-Mehta/Mehak-Mehta' }}
          output_action: pull-request
          
      - name: ðŸ“Œ plugin lines (mastered)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.lines.masteredd.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_lines: yes
      
      - name: ðŸ“Œ plugin music (mastered)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.music.masteredd.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_music: yes
          plugin_music_user: Light
          plugin_music_provider: spotify
          plugin_music_limit: 4                  # Limit to 4 entries
          plugin_music_playlist: ${{ secrets.MUSIC_PLAYLIST }}
      - name: ðŸ“Œ plugin people (mastered)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.people.masteredd.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_people: yes
          plugin_people_types: thanks     # Display followers and "thanks" sections
          plugin_people_limit: 28                    # Limit to 28 entries per section
          plugin_people_size: 28                     # Size in pixels of displayed avatars
          plugin_people_identicons: no               # Use avatars (do not use identicons)
          plugin_people_thanks: Mehak-Mehta, lowlighter, snoopy70617, octocat  # Users that will be displayed in "thanks" section
          plugin_people_sponsors_custom: octocat     # Users that will be displayed additionally in "sponsors" section
          plugin_people_shuffle: yes    
          
          # Shuffle for varied output
      - name: ðŸ“Œ plugin anime (mastered)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.anime.masteredd.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_anilist: yes
          plugin_anilist_medias: anime, manga             # Display both animes and mangas
          plugin_anilist_sections: favorites, characters  # Display only favorites and characters sections
          plugin_anilist_limit: 2                         # Limit to 2 entry per section (characters section excluded)
          plugin_anilist_shuffle: yes                     # Shuffle data for more varied outputs
          plugin_anilist_user: lightyagami123                # Use same username as GitHub login
          plugin_anilist_limit_characters: 22        
